import { QuizQuestion, QuizSession } from "./types";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ── 1. Environment ──────────────────────────────────────────────
  {
    id: "environment",
    title: "Pick the place that feels most like you",
    subtitle: "Don't overthink it — go with your gut",
    type: "single",
    options: [
      {
        id: "forest",
        label: "A quiet forest",
        description: "Tall trees, damp earth, dappled sunlight",
        emoji: "🌲",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: -0.2, classicAvantgarde: -0.2, intimateProjecting: -0.1 },
        accordBoosts: ["Woody", "Green", "Earthy", "Mossy"],
      },
      {
        id: "beach",
        label: "A sun-warmed beach",
        description: "Salt air, warm sand, endless horizon",
        emoji: "🏖️",
        dimensionShifts: { warmthFreshness: -0.3, boldnessSubtlety: -0.1, classicAvantgarde: -0.1, intimateProjecting: 0.2 },
        accordBoosts: ["Aquatic", "Citrus", "Fresh", "Ozonic"],
      },
      {
        id: "rooftop",
        label: "A city rooftop at night",
        description: "Skyline lights, cool air, endless possibility",
        emoji: "🌃",
        dimensionShifts: { warmthFreshness: -0.1, boldnessSubtlety: 0.3, classicAvantgarde: 0.3, intimateProjecting: 0.2 },
        accordBoosts: ["Aromatic", "Metallic", "Spicy", "Synthetic"],
      },
      {
        id: "cabin",
        label: "A cozy cabin",
        description: "Crackling fire, soft blankets, warm drinks",
        emoji: "🏡",
        dimensionShifts: { warmthFreshness: 0.4, boldnessSubtlety: -0.2, classicAvantgarde: -0.2, intimateProjecting: -0.3 },
        accordBoosts: ["Amber", "Vanilla", "Warm Spicy", "Resin"],
      },
      {
        id: "garden",
        label: "A blooming garden",
        description: "Petals, herbs, morning dew on leaves",
        emoji: "🌸",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: -0.2, classicAvantgarde: -0.1, intimateProjecting: -0.1 },
        accordBoosts: ["Floral", "Green", "Rose", "Herbal"],
      },
    ],
  },

  // ── 2. Texture ──────────────────────────────────────────────────
  {
    id: "texture",
    title: "Choose the texture that draws you in",
    subtitle: "Imagine running your fingers across it",
    type: "single",
    options: [
      {
        id: "silk",
        label: "Silk",
        description: "Smooth, cool, and luminous",
        emoji: "✨",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: -0.1, classicAvantgarde: 0.2, intimateProjecting: -0.2 },
        accordBoosts: ["Powdery", "Musk", "Iris"],
      },
      {
        id: "leather",
        label: "Leather",
        description: "Supple, strong, and timeless",
        emoji: "🖤",
        dimensionShifts: { warmthFreshness: 0.2, boldnessSubtlety: 0.4, classicAvantgarde: 0.1, intimateProjecting: 0.2 },
        accordBoosts: ["Leather", "Smoky", "Oud", "Spicy"],
      },
      {
        id: "linen",
        label: "Linen",
        description: "Light, clean, and breezy",
        emoji: "🤍",
        dimensionShifts: { warmthFreshness: -0.3, boldnessSubtlety: -0.3, classicAvantgarde: -0.1, intimateProjecting: -0.1 },
        accordBoosts: ["Clean", "Fresh", "Ozonic", "Citrus"],
      },
      {
        id: "velvet",
        label: "Velvet",
        description: "Rich, plush, and indulgent",
        emoji: "💜",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: 0.1, classicAvantgarde: -0.1, intimateProjecting: -0.3 },
        accordBoosts: ["Amber", "Vanilla", "Sweet", "Resin"],
      },
      {
        id: "wool",
        label: "Wool",
        description: "Warm, textured, and grounding",
        emoji: "🧶",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: -0.1, classicAvantgarde: -0.3, intimateProjecting: -0.2 },
        accordBoosts: ["Woody", "Warm Spicy", "Earthy", "Amber"],
      },
    ],
  },

  // ── 3. Time of Day ──────────────────────────────────────────────
  {
    id: "time",
    title: "When do you feel most like yourself?",
    subtitle: "The hour when your energy peaks",
    type: "single",
    options: [
      {
        id: "dawn",
        label: "Dawn",
        description: "The world is waking up — everything feels possible",
        emoji: "🌅",
        dimensionShifts: { warmthFreshness: -0.2, boldnessSubtlety: -0.2, classicAvantgarde: -0.1, intimateProjecting: -0.2 },
        accordBoosts: ["Fresh", "Citrus", "Green", "Ozonic"],
      },
      {
        id: "midday",
        label: "Midday",
        description: "Peak energy, bright light, full momentum",
        emoji: "☀️",
        dimensionShifts: { warmthFreshness: -0.1, boldnessSubtlety: 0.1, classicAvantgarde: -0.2, intimateProjecting: 0.2 },
        accordBoosts: ["Citrus", "Aromatic", "Fresh", "Aquatic"],
      },
      {
        id: "golden-hour",
        label: "Golden hour",
        description: "Everything glows — the magic between day and night",
        emoji: "🌇",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: 0.1, classicAvantgarde: -0.1, intimateProjecting: 0.1 },
        accordBoosts: ["Amber", "Warm", "Floral", "Musky"],
      },
      {
        id: "dusk",
        label: "Dusk",
        description: "Shadows lengthen, the air cools, mystery beckons",
        emoji: "🌆",
        dimensionShifts: { warmthFreshness: 0.2, boldnessSubtlety: 0.2, classicAvantgarde: 0.1, intimateProjecting: -0.1 },
        accordBoosts: ["Incense", "Smoky", "Warm Spicy", "Woody"],
      },
      {
        id: "midnight",
        label: "Midnight",
        description: "The world is quiet and you're wide awake",
        emoji: "🌙",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: 0.4, classicAvantgarde: 0.3, intimateProjecting: -0.2 },
        accordBoosts: ["Oud", "Incense", "Dark", "Leather"],
      },
    ],
  },

  // ── 4. Music ────────────────────────────────────────────────────
  {
    id: "music",
    title: "Pick the music that matches your energy",
    subtitle: "What's playing in the background of your ideal day?",
    type: "single",
    options: [
      {
        id: "jazz",
        label: "Jazz",
        description: "Smoky clubs, improvisation, quiet sophistication",
        emoji: "🎷",
        dimensionShifts: { warmthFreshness: 0.2, boldnessSubtlety: 0.1, classicAvantgarde: -0.2, intimateProjecting: -0.3 },
        accordBoosts: ["Smoky", "Woody", "Warm Spicy", "Leather"],
      },
      {
        id: "electronic",
        label: "Electronic",
        description: "Pulsing beats, neon energy, future forward",
        emoji: "🎧",
        dimensionShifts: { warmthFreshness: -0.2, boldnessSubtlety: 0.3, classicAvantgarde: 0.4, intimateProjecting: 0.3 },
        accordBoosts: ["Synthetic", "Metallic", "Aromatic", "Ozonic"],
      },
      {
        id: "classical",
        label: "Classical",
        description: "Timeless elegance, layered complexity, emotional depth",
        emoji: "🎻",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: -0.1, classicAvantgarde: -0.4, intimateProjecting: 0.2 },
        accordBoosts: ["Floral", "Powdery", "Amber", "Rose"],
      },
      {
        id: "indie",
        label: "Indie / Alternative",
        description: "Off the beaten path, authentic, interesting",
        emoji: "🎸",
        dimensionShifts: { warmthFreshness: -0.1, boldnessSubtlety: -0.1, classicAvantgarde: 0.3, intimateProjecting: -0.2 },
        accordBoosts: ["Green", "Herbal", "Earthy", "Tea"],
      },
      {
        id: "rnb",
        label: "R&B / Soul",
        description: "Sensual, smooth, emotionally rich",
        emoji: "🎤",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: 0.2, classicAvantgarde: -0.1, intimateProjecting: 0.1 },
        accordBoosts: ["Musky", "Vanilla", "Sweet", "Amber"],
      },
    ],
  },

  // ── 5. Impression ───────────────────────────────────────────────
  {
    id: "impression",
    title: "How do you want people to remember meeting you?",
    subtitle: "The feeling you leave behind",
    type: "single",
    options: [
      {
        id: "warm",
        label: "Warm",
        description: "Like being wrapped in a hug — safe and comforting",
        emoji: "🤗",
        dimensionShifts: { warmthFreshness: 0.4, boldnessSubtlety: -0.1, classicAvantgarde: -0.1, intimateProjecting: -0.1 },
        accordBoosts: ["Vanilla", "Amber", "Warm", "Soft"],
      },
      {
        id: "intriguing",
        label: "Intriguing",
        description: "There's always more to discover about you",
        emoji: "🔮",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: 0.2, classicAvantgarde: 0.3, intimateProjecting: -0.2 },
        accordBoosts: ["Incense", "Oud", "Smoky", "Resin"],
      },
      {
        id: "confident",
        label: "Confident",
        description: "You walk into a room and own it naturally",
        emoji: "💪",
        dimensionShifts: { warmthFreshness: 0, boldnessSubtlety: 0.4, classicAvantgarde: 0.1, intimateProjecting: 0.3 },
        accordBoosts: ["Leather", "Spicy", "Woody", "Aromatic"],
      },
      {
        id: "approachable",
        label: "Approachable",
        description: "Easy to talk to, easy to be around",
        emoji: "😊",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: -0.3, classicAvantgarde: -0.2, intimateProjecting: -0.1 },
        accordBoosts: ["Fresh", "Citrus", "Clean", "Floral"],
      },
      {
        id: "unforgettable",
        label: "Unforgettable",
        description: "They'll think about you long after you've left",
        emoji: "⭐",
        dimensionShifts: { warmthFreshness: 0.1, boldnessSubtlety: 0.3, classicAvantgarde: 0.2, intimateProjecting: 0.4 },
        accordBoosts: ["Tuberose", "Oud", "Amber", "Sweet"],
      },
    ],
  },

  // ── 6. Season ───────────────────────────────────────────────────
  {
    id: "season",
    title: "What season speaks to your soul?",
    subtitle: "The one you'd live in year-round if you could",
    type: "single",
    options: [
      {
        id: "spring",
        label: "Spring",
        description: "Fresh starts, blooming flowers, gentle rain",
        emoji: "🌷",
        dimensionShifts: { warmthFreshness: -0.1, boldnessSubtlety: -0.2, classicAvantgarde: -0.1, intimateProjecting: 0.1 },
        accordBoosts: ["Floral", "Green", "Fresh", "Rose"],
        familyBoosts: { Fresh: 0.3, Floral: 0.3 },
      },
      {
        id: "summer",
        label: "Summer",
        description: "Long days, golden skin, carefree energy",
        emoji: "🌞",
        dimensionShifts: { warmthFreshness: -0.2, boldnessSubtlety: 0.1, classicAvantgarde: 0, intimateProjecting: 0.2 },
        accordBoosts: ["Citrus", "Aquatic", "Tropical", "Coconut"],
        familyBoosts: { Fresh: 0.3, Citrus: 0.3 },
      },
      {
        id: "autumn",
        label: "Autumn",
        description: "Crisp air, warm colors, cozy layers",
        emoji: "🍂",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: 0.1, classicAvantgarde: -0.1, intimateProjecting: -0.1 },
        accordBoosts: ["Woody", "Warm Spicy", "Amber", "Earthy"],
        familyBoosts: { Woody: 0.3, Amber: 0.3 },
      },
      {
        id: "winter",
        label: "Winter",
        description: "Quiet nights, deep warmth, rich indulgence",
        emoji: "❄️",
        dimensionShifts: { warmthFreshness: 0.3, boldnessSubtlety: 0.2, classicAvantgarde: 0, intimateProjecting: -0.2 },
        accordBoosts: ["Incense", "Vanilla", "Oud", "Resin"],
        familyBoosts: { Oriental: 0.3, Amber: 0.3 },
      },
    ],
  },

  // ── 7. Experience Level (branching) ─────────────────────────────
  {
    id: "experience",
    title: "How familiar are you with fragrance?",
    subtitle: "No wrong answer — this helps us calibrate your results",
    type: "single",
    options: [
      {
        id: "beginner",
        label: "Just getting started",
        description: "I want to find my first great fragrance",
        emoji: "🌱",
        dimensionShifts: {},
      },
      {
        id: "intermediate",
        label: "I know what I like",
        description: "I own a few fragrances and have preferences",
        emoji: "🌿",
        dimensionShifts: {},
      },
      {
        id: "enthusiast",
        label: "Fragrance enthusiast",
        description: "I know my notes, families, and houses",
        emoji: "🌳",
        dimensionShifts: {},
      },
    ],
  },

  // ── 8a. Priorities (beginner branch) ────────────────────────────
  {
    id: "priorities",
    title: "What matters most to you in a fragrance?",
    subtitle: "Pick up to 2 — we'll use these to fine-tune your matches",
    type: "multi",
    maxSelections: 2,
    condition: (session: QuizSession) => session.experience === "beginner",
    options: [
      {
        id: "smells-good",
        label: "Smells amazing on me",
        description: "Chemistry matters — I want compliments",
        emoji: "💫",
        dimensionShifts: { intimateProjecting: -0.2, classicAvantgarde: -0.1 },
      },
      {
        id: "lasts-long",
        label: "Lasts all day",
        description: "I don't want to reapply constantly",
        emoji: "⏳",
        dimensionShifts: { boldnessSubtlety: 0.2, intimateProjecting: 0.2 },
      },
      {
        id: "compliments",
        label: "Gets compliments",
        description: "I want people to notice and ask about it",
        emoji: "💬",
        dimensionShifts: { intimateProjecting: 0.3, boldnessSubtlety: 0.1 },
      },
      {
        id: "unique",
        label: "Unique and different",
        description: "I don't want to smell like everyone else",
        emoji: "🦄",
        dimensionShifts: { classicAvantgarde: 0.3, boldnessSubtlety: 0.1 },
      },
    ],
  },

  // ── 8b. Families (enthusiast branch) ────────────────────────────
  {
    id: "families",
    title: "Which scent families do you gravitate toward?",
    subtitle: "Pick up to 3 families you love",
    type: "multi",
    maxSelections: 3,
    condition: (session: QuizSession) => session.experience === "enthusiast",
    options: [
      {
        id: "Fresh",
        label: "Fresh",
        description: "Citrus, aquatic, clean, and invigorating",
        emoji: "🍋",
        dimensionShifts: { warmthFreshness: -0.2 },
        familyBoosts: { Fresh: 0.5, Citrus: 0.3 },
      },
      {
        id: "Floral",
        label: "Floral",
        description: "Rose, jasmine, tuberose, iris",
        emoji: "🌹",
        dimensionShifts: { warmthFreshness: 0.1 },
        familyBoosts: { Floral: 0.5 },
      },
      {
        id: "Amber",
        label: "Amber / Oriental",
        description: "Vanilla, benzoin, warm resins, spices",
        emoji: "🍯",
        dimensionShifts: { warmthFreshness: 0.3 },
        familyBoosts: { Amber: 0.5, Oriental: 0.3 },
      },
      {
        id: "Woody",
        label: "Woody",
        description: "Sandalwood, cedar, vetiver, patchouli",
        emoji: "🪵",
        dimensionShifts: { warmthFreshness: 0.1 },
        familyBoosts: { Woody: 0.5 },
      },
      {
        id: "Aromatic",
        label: "Aromatic / Fougère",
        description: "Lavender, herbs, clean aromatics",
        emoji: "🌿",
        dimensionShifts: { classicAvantgarde: -0.1 },
        familyBoosts: { Aromatic: 0.5, Fresh: 0.2 },
      },
    ],
  },

  // ── 9. Intensity ────────────────────────────────────────────────
  {
    id: "intensity",
    title: "How strong should your fragrance be?",
    subtitle: "Think about how you want it to project",
    type: "single",
    options: [
      {
        id: "light",
        label: "Barely there",
        description: "A whisper — only noticeable up close",
        emoji: "🕊️",
        dimensionShifts: { boldnessSubtlety: -0.3, intimateProjecting: -0.3 },
      },
      {
        id: "moderate",
        label: "Noticeable",
        description: "Present but not overwhelming — balanced",
        emoji: "🌊",
        dimensionShifts: {},
      },
      {
        id: "bold",
        label: "Commanding",
        description: "Makes a statement — fills a room",
        emoji: "🔥",
        dimensionShifts: { boldnessSubtlety: 0.3, intimateProjecting: 0.3 },
      },
    ],
  },

  // ── 10. Occasion ────────────────────────────────────────────────
  {
    id: "occasion",
    title: "When will you wear this most?",
    subtitle: "Pick up to 3 occasions",
    type: "multi",
    maxSelections: 3,
    options: [
      {
        id: "everyday",
        label: "Everyday",
        description: "Your daily signature — versatile and reliable",
        emoji: "☕",
        dimensionShifts: { classicAvantgarde: -0.1, intimateProjecting: -0.1 },
      },
      {
        id: "work",
        label: "Work / Office",
        description: "Professional and polished — not distracting",
        emoji: "💼",
        dimensionShifts: { boldnessSubtlety: -0.1, classicAvantgarde: -0.2 },
      },
      {
        id: "date-night",
        label: "Date night",
        description: "Romantic, alluring, and memorable",
        emoji: "🕯️",
        dimensionShifts: { warmthFreshness: 0.2, intimateProjecting: -0.2 },
      },
      {
        id: "special-event",
        label: "Special events",
        description: "When you want to make an impression",
        emoji: "🥂",
        dimensionShifts: { boldnessSubtlety: 0.1, intimateProjecting: 0.1 },
      },
      {
        id: "outdoor",
        label: "Outdoor / Active",
        description: "Fresh, light, and energizing",
        emoji: "🏃",
        dimensionShifts: { warmthFreshness: -0.2, boldnessSubtlety: -0.1 },
      },
    ],
  },
];
